M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-07-03T00:47:10-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-03T00:47:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.350
%
G90
G05
T1
X65.019Y-82.62
X76.451Y-82.62
M30
