M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-07-07T00:06:34-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-07T00:06:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.300
%
G90
G05
T1
X110.0Y-72.785
X110.0Y-84.215
M30
